In [4]:
import json
import pandas as pd
from pprint import pprint

In [16]:
with open('Resources/city.list.json', 'r',encoding='utf-8') as jsonfile:
    jsndata = json.load(jsonfile)

ids = []
cit = []
lat = []
lon = []

for i in range(len(jsndata)):
    if jsndata[i]['country'] == 'US':
        ids.append(jsndata[i]['id'])
        cit.append(jsndata[i]['name'])
        lat.append(jsndata[i]['coord']['lat'])
        lon.append(jsndata[i]['coord']['lon'])

dftemp = pd.DataFrame({'ID':ids,'City':cit,'Latitude':lat,'Longitude':lon})
dftemp.to_csv("Resources/uscities-all.csv", index=False, header=True)

In [5]:
uscities_all = pd.read_csv("Resources/uscities-all.csv", encoding="utf-8")
print(f"# of US cities: {len(uscities_all)}")
uscities_all.head()

# of US cities: 19972

        ID               City   Latitude   Longitude
0  4070245   Jones Crossroads  31.210730  -85.484657
1  4344544      Vernon Parish  31.116850  -93.183502
2  4215307            Pennick  31.313000  -81.558990
3  5285039  Black Bear Spring  31.386209 -110.288139
4  4673179          Bee House  31.402660  -98.081139

In [16]:
uscities_major = pd.read_csv("Resources/uscities-major.csv", encoding="utf-8")
print(f"# of major US cities: {len(uscities_major)}")
uscities_major.head()

# of major US cities: 100

           City         State
0      New York      New York
1   Los Angeles    California
2       Chicago      Illinois
3       Houston         Texas
4  Philadelphia  Pennsylvania

In [23]:
citylist = uscities_all['City'].tolist()
ids = []
lat = []
lon = []
for city in uscities_major['City']:
    try:
        icity = citylist.index(city)
        ids.append(uscities_all['ID'][icity])
        lat.append(uscities_all['Latitude'][icity])
        lon.append(uscities_all['Longitude'][icity])
    except:
        ids.append("")
        lat.append("")
        lon.append("")
uscities_major['ID'] = ids
uscities_major['Latitude'] = lat
uscities_major['Longitude'] = lon

In [24]:
uscities_major

               City                 State       ID Latitude Longitude
0          New York              New York  5128638  43.0004  -75.4999
1       Los Angeles            California  5368361  34.0522  -118.244
2           Chicago              Illinois  4887398    41.85    -87.65
3           Houston                 Texas  4699066  29.7633  -95.3633
4      Philadelphia          Pennsylvania  4560349  39.9523  -75.1638
5           Phoenix               Arizona  5308655  33.4484  -112.074
6       San Antonio                 Texas  4726206  29.4241  -98.4936
7         San Diego            California  5391811  32.7153  -117.157
8            Dallas                 Texas  4684888  32.7831  -96.8067
9          San Jose            California  5392171  37.3394  -121.895
10           Austin                 Texas  4254010  38.7584   -85.808
11     Jacksonville               Florida  4241704  39.7339   -90.229
12    San Francisco            California  5391959  37.7749  -122.419
13     Indianapolis               Indiana  4861716  41.3969  -92.4335
14         Columbus                  Ohio  4256038  39.2014  -85.9214
15       Fort Worth                 Texas  4691930  32.7254  -97.3208
16        Charlotte        North Carolina  4460243  35.2271  -80.8431
17          Seattle            Washington  5809844  47.6062  -122.332
18           Denver              Colorado  4463523  35.5312  -81.0298
19          El Paso                 Texas  5520993  31.7587  -106.487
20          Detroit              Michigan  4990729  42.3314  -83.0458
21       Washington  District of Columbia  5815135  47.5001  -120.501
22           Boston         Massachusetts  4317656  29.8833  -92.0557
23          Memphis             Tennessee  4641239  35.1495   -90.049
24        Nashville             Tennessee  5003243  42.6028   -85.093
25         Portland                Oregon  4720131  27.8773  -97.3239
26    Oklahoma City              Oklahoma  4544349  35.4676  -97.5164
27        Las Vegas                Nevada  5506956   36.175  -115.137
28        Baltimore              Maryland  4347778  39.2904  -76.6122
29       Louisville              Kentucky  4299276  38.2542  -85.7594
..              ...                   ...      ...      ...       ...
70           Toledo                  Ohio  5174035  41.6639  -83.5552
71          Lincoln              Nebraska  5072006     40.8   -96.667
72          Orlando               Florida  4167147  28.5383  -81.3792
73      Chula Vista            California  5336899    32.64  -117.084
74      Jersey City            New Jersey  5099836  40.7282  -74.0776
75         Chandler               Arizona  4049176  39.3003  -94.3827
76       Fort Wayne               Indiana  4920423  41.1306  -85.1289
77          Buffalo              New York  5819881  44.3483  -106.699
78           Durham        North Carolina  4464368   35.994  -78.8986
79   St. Petersburg               Florida
80           Irvine            California  5257570  44.9255  -91.4199
81           Laredo                 Texas  4705349  27.5064  -99.5075
82          Lubbock                 Texas  5525577  33.5779  -101.855
83          Madison             Wisconsin  4434663  32.4618  -90.1154
84          Gilbert               Arizona  5295903  33.3528  -111.789
85          Norfolk              Virginia  5073965  42.0283   -97.417
86             Reno                Nevada  5511077  39.5296  -119.814
87    Winston-Salem        North Carolina  4499612  36.0999  -80.2442
88         Glendale               Arizona  5577409  40.0819  -105.366
89          Hialeah               Florida  4158476  25.8576  -80.2781
90          Garland                 Texas  4693003  32.9126  -96.6389
91       Scottsdale               Arizona  5313457  33.5092  -111.899
92           Irving                 Texas  4700168   32.814  -96.9489
93       Chesapeake              Virginia  4752186   36.819  -76.2749
94  North Las Vegas                Nevada  5509403  36.1989  -115.118
95          Fremont            California  4920512  41.7309  -84.9327
96      Baton Rouge             Louisiana  4315588  30.4507  -91.1545
97         Richmond              Virginia  4305974  37.7479  -84.2946
98            Boise                 Idaho  5586437  43.6135  -116.203
99   San Bernardino            California  5391710  34.1083   -117.29

[100 rows x 5 columns]

In [25]:
uscities_major.to_csv("Resources/uscities.csv", index=False, header=True)

               City                 State       ID Latitude Longitude
0          New York              New York  4070245  31.2107  -85.4847
1       Los Angeles            California  4070245  31.2107  -85.4847
2           Chicago              Illinois  4070245  31.2107  -85.4847
3           Houston                 Texas  4070245  31.2107  -85.4847
4      Philadelphia          Pennsylvania  4070245  31.2107  -85.4847
5           Phoenix               Arizona  4070245  31.2107  -85.4847
6       San Antonio                 Texas  4070245  31.2107  -85.4847
7         San Diego            California  4070245  31.2107  -85.4847
8            Dallas                 Texas  4070245  31.2107  -85.4847
9          San Jose            California  4070245  31.2107  -85.4847
10           Austin                 Texas  4070245  31.2107  -85.4847
11     Jacksonville               Florida  4070245  31.2107  -85.4847
12    San Francisco            California  4070245  31.2107  -85.4847
13     Indianapolis               Indiana  4070245  31.2107  -85.4847
14         Columbus                  Ohio  4070245  31.2107  -85.4847
15       Fort Worth                 Texas  4070245  31.2107  -85.4847
16        Charlotte        North Carolina  4070245  31.2107  -85.4847
17          Seattle            Washington  4070245  31.2107  -85.4847
18           Denver              Colorado  4070245  31.2107  -85.4847
19          El Paso                 Texas  4070245  31.2107  -85.4847
20          Detroit              Michigan  4070245  31.2107  -85.4847
21       Washington  District of Columbia  4070245  31.2107  -85.4847
22           Boston         Massachusetts  4070245  31.2107  -85.4847
23          Memphis             Tennessee  4070245  31.2107  -85.4847
24        Nashville             Tennessee  4070245  31.2107  -85.4847
25         Portland                Oregon  4070245  31.2107  -85.4847
26    Oklahoma City              Oklahoma  4070245  31.2107  -85.4847
27        Las Vegas                Nevada  4070245  31.2107  -85.4847
28        Baltimore              Maryland  4070245  31.2107  -85.4847
29       Louisville              Kentucky  4070245  31.2107  -85.4847
..              ...                   ...      ...      ...       ...
70           Toledo                  Ohio  4070245  31.2107  -85.4847
71          Lincoln              Nebraska  4070245  31.2107  -85.4847
72          Orlando               Florida  4070245  31.2107  -85.4847
73      Chula Vista            California  4070245  31.2107  -85.4847
74      Jersey City            New Jersey  4070245  31.2107  -85.4847
75         Chandler               Arizona  4070245  31.2107  -85.4847
76       Fort Wayne               Indiana  4070245  31.2107  -85.4847
77          Buffalo              New York  4070245  31.2107  -85.4847
78           Durham        North Carolina  4070245  31.2107  -85.4847
79   St. Petersburg               Florida
80           Irvine            California  4070245  31.2107  -85.4847
81           Laredo                 Texas  4070245  31.2107  -85.4847
82          Lubbock                 Texas  4070245  31.2107  -85.4847
83          Madison             Wisconsin  4070245  31.2107  -85.4847
84          Gilbert               Arizona  4070245  31.2107  -85.4847
85          Norfolk              Virginia  4070245  31.2107  -85.4847
86             Reno                Nevada  4070245  31.2107  -85.4847
87    Winston-Salem        North Carolina  4070245  31.2107  -85.4847
88         Glendale               Arizona  4070245  31.2107  -85.4847
89          Hialeah               Florida  4070245  31.2107  -85.4847
90          Garland                 Texas  4070245  31.2107  -85.4847
91       Scottsdale               Arizona  4070245  31.2107  -85.4847
92           Irving                 Texas  4070245  31.2107  -85.4847
93       Chesapeake              Virginia  4070245  31.2107  -85.4847
94  North Las Vegas                Nevada  4070245  31.2107  -85.4847
95          Fremont            California  4070245  31.2107  -85.4847
96      Baton Rouge             Louisiana  4070245  31.2107  -85.4847
97         Richmond              Virginia  4070245  31.2107  -85.4847
98            Boise                 Idaho  4070245  31.2107  -85.4847
99   San Bernardino            California  4070245  31.2107  -85.4847

[100 rows x 5 columns]